-- Supabase Database Schema for Naskly CRM

-- 1. Create Clients Table
CREATE TABLE IF NOT EXISTS public.clients (
    id TEXT PRIMARY KEY, -- ID in format N001, N002, etc.
    created_at TIMESTAMPTZ DEFAULT NOW(),
    booking_date DATE,
    delivery_date DATE,
    client_name TEXT NOT NULL,
    whatsapp TEXT NOT NULL,
    source TEXT DEFAULT 'WhatsApp',
    deal_owner TEXT,
    delivery_staff TEXT,
    service_type TEXT, -- Comma-separated or string list
    service_specs TEXT,
    total_price NUMERIC(12,2) DEFAULT 0,
    paid NUMERIC(12,2) DEFAULT 0,
    remaining NUMERIC(12,2) DEFAULT 0,
    delivery_status TEXT DEFAULT 'لم تبدأ بعد', -- 'لم تبدأ بعد', 'جزئي', 'تم بالكامل'
    payment_status TEXT DEFAULT 'لم يتم استلام مبالغ' -- 'لم يتم استلام مبالغ', 'جزئي', 'تم بالكامل'
);

-- 2. Create Team Members Table
CREATE TABLE IF NOT EXISTS public.team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Services Table
CREATE TABLE IF NOT EXISTS public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

-- 5. Open Access Policies (for anonymous public access via anon key)
CREATE POLICY "Public full access to clients" ON public.clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access to team_members" ON public.team_members FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access to services" ON public.services FOR ALL USING (true) WITH CHECK (true);

-- 6. Insert Default Team Members & Services
INSERT INTO public.team_members (name) VALUES 
    ('أحمد'),
    ('محمد'),
    ('محمود'),
    ('سارة')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.services (name) VALUES 
    ('تصميم هوية بصرية'),
    ('إدارة حملات إعلانية'),
    ('تطوير موقع إلكتروني'),
    ('إنتاج فيديو موشن جرافيك')
ON CONFLICT (name) DO NOTHING;
